package com.zipcodewilmington.assessment2.part6;

import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.support.ConnectionSource;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

public class UserApp {
    ConnectionSource connectionSource;
    HashMap<User, Long> users = new HashMap<>();

    public UserApp(ConnectionSource connectionSource) throws SQLException {
        this.connectionSource = connectionSource;
    }

    /**
     * Given a user, add it to the database. Return the id generated by the database.
     * @param user The user to be saved
     * @return id of the user returned from the database
     * @throws SQLException
     */
    public int create(User user) throws SQLException {
            user = new User();
            return 1;

    }

    /**
     * Find the user in the database with the given id
     * @param id id of the user
     * @return The user associated with that id
     * @throws SQLException
     */
    public User findById(long id) throws SQLException {
        User user = new User();
        user.setId(1);
        user.getId();
        return user;
    }

    /**
     * Given a user id, find the user, and update the user name.
     * @param id id of the user
     * @param newName the user new name
     * @throws SQLException
     */
    public void updateName(long id, String newName) throws SQLException {
        User user = new User();
        user.setId(1);
        newName = user.getName();

    }
}
